echo 1
./cub3D maps/bad/color_invalid_rgb.cub
echo 2
./cub3D maps/bad/color_missing.cub
echo 3
./cub3D maps/bad/color_missing_ceiling_rgb.cub
echo 4
./cub3D maps/bad/color_missing_floor_rgb.cub
echo 5
./cub3D maps/bad/color_none.cub
echo 6
./cub3D maps/bad/empty.cub
echo 7
./cub3D maps/bad/file_letter_end.cub
echo 8
./cub3D maps/bad/filetype_missing
echo 9
./cub3D maps/bad/filetype_wrong.buc
echo 10
./cub3D maps/bad/forbidden.cub
echo 1
./cub3D maps/bad/map_first.cub
echo 12
./cub3D maps/bad/map_middle.cub
echo 13
./cub3D maps/bad/map_missing.cub
echo 14
./cub3D maps/bad/map_too_small.cub
echo 15
./cub3D maps/bad/player_multiple.cub
echo 16
./cub3D maps/bad/player_none.cub
echo 17
./cub3D maps/bad/map_only.cub
echo 18
./cub3D maps/bad/player_on_edge.cub
echo 19
./cub3D maps/bad/textures_dir.cub
echo 20
./cub3D maps/bad/textures_duplicates.cub
echo 21
./cub3D maps/bad/textures_forbidden.cub
echo 22
./cub3D maps/bad/textures_invalid.cub
echo 23
./cub3D maps/bad/textures_missing.cub
echo 24
./cub3D maps/bad/textures_none.cub
echo 25
./cub3D maps/bad/textures_not_xpm.cub
echo 26
./cub3D maps/bad/wall_hole_east.cub
echo 27
./cub3D maps/bad/wall_hole_north.cub
echo 28
./cub3D maps/bad/wall_hole_south.cub
echo 29
./cub3D maps/bad/wall_hole_west.cub
echo 30
./cub3D maps/bad/wall_none.cub


