echo 1
./cub3D maps/invalid/color_256.cub
echo 2
./cub3D maps/invalid/color_alphabet.cub
echo 3
./cub3D maps/invalid/color_duplicate.cub
echo 4
./cub3D maps/invalid/color_empty.cub
echo 5
./cub3D maps/invalid/color_missingblue.cub
echo 6
./cub3D maps/invalid/color_negative.cub
echo 7
./cub3D maps/invalid/color_nocomma.cub
echo 8
./cub3D maps/invalid/color_undermap.cub
echo 9
./cub3D maps/invalid/color_wrongidentifier.cub
echo 10
./cub3D maps/invalid/empty.cub
echo 11
./cub3D maps/invalid/map_empty.cub
echo 12
./cub3D maps/invalid/map_invalidchar.cub
echo 13
./cub3D maps/invalid/map_missing_player.cub
echo 14
./cub3D maps/invalid/map_unwarppedE.cub
echo 15
./cub3D maps/invalid/map_unwarppedN.cub
echo 16
./cub3D maps/invalid/map_unwarppedS.cub
echo 17
./cub3D maps/invalid/map_unwarppedW.cub
echo 18
./cub3D maps/invalid/map_wrongplayer.cub
echo 19
./cub3D maps/invalid/tex_empty.cub
echo 20
./cub3D maps/invalid/tex_invalidchars.cub
echo 21
./cub3D maps/invalid/tex_missingfile.cub
echo 22
./cub3D maps/invalid/tex_missingside.cub
echo 23
./cub3D maps/invalid/tex_pathgaps.cub
echo 24
./cub3D maps/invalid/tex_undermap.cub
echo 25
./cub3D maps/invalid/test_file.cub
